### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by TheGreatDictatorer** [developersu/Tihwin#10]
Heya, sorry if this is getting a bit bothersome, but I notice this issue when I was trying to run the JAR program, when I tried to hit convert/install the program gave me the error saying that the operation was not permitted. Is there a work around to this?
<img width="688" alt="Screen Shot 2023-09-25 at 2 23 34 AM" src="https://github.com/developersu/Tihwin/assets/46411307/188a5c44-f4f4-44d4-bb75-702c5c76d67f">

**Comment by developersu** [comment]
You don't have rights to write into `/Volumes/SSD PS2`. Use another folder that you have rights to write or grant access. Should be something [like this](https://superuser.com/questions/1595874/operation-not-permitted-using-find-in-macos-terminal).
