### ISSUE TITLE
Unsure of Things

### ISSUE THREAD

**Issue by TheGreatDictatorer** [developersu/Tihwin#7]
Heya! Sorry if your unable to help me, but I'm quite confused as to how exactly I am supposed to run Tihwin on mac, as I am fairly new to the whole using Java. So is it possible for you to explain how exactly I can either run or at least install the program onto my mac? Using a Cathalina at the moment, so I'm quite unsure of how exactly things work.

**Comment by developersu** [comment]
Hi. Just download JAR, double click on it and follow the instructions: OS would ask you to download and install Java runtime or development kit and after that you'll be able to execute application.

**Comment by TheGreatDictatorer** [comment]
Whats JAR?

**Comment by developersu** [comment]
![IMG_20230924_131958.jpg](https://github.com/developersu/Tihwin/assets/1172602/bfcd5b88-e798-4c65-ba11-805581731353)

**Comment by TheGreatDictatorer** [comment]
Okay gotcha, got it working now. Though got another question, well recommendation anyways. Got any recommendations for an alt for OPL manager for mac?

**Comment by developersu** [comment]
U'r already use the best one
